# Generated by Django 4.0.6 on 2022-08-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_brands_shop', '0004_customer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
    ]
