# Generated by Django 4.0.6 on 2022-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_brands_shop', '0006_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True, verbose_name='Товар'),
        ),
    ]
