# Generated by Django 4.0.6 on 2022-08-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_brands_shop', '0007_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='size',
            field=models.CharField(choices=[('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl')], max_length=40, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True, verbose_name='Время заказа'),
        ),
    ]
