# Generated by Django 4.0.6 on 2022-08-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_brands_shop', '0008_alter_balance_size_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sex',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('м', 'Мужские'), ('ж', 'Женские'), ('у', 'Унисекс')], default='Мужские', max_length=30, verbose_name='Пол'),
        ),
    ]
